image:
  repository: kong/kong-gateway
  tag: "2.6.0.0-alpine"

env:
  database: postgres
  pg_user: kong
  pg_password: kong
  pg_database: kong
  admin_api_uri: "https://kong-admin.k3s.local"
  admin_gui_url: "https://kong-manager.k3s.local"
  portal_gui_host: "kong-portal.k3s.local"
  portal_gui_protocol: "https"
  portal_api_url: "https://portalapi.k3s.local"
  
  role: control_plane
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key

  password:
    valueFrom:
      secretKeyRef:
        name: kong-enterprise-superuser-password
        key: password

  portal_session_conf:
    valueFrom:
      secretKeyRef:
        name: kong-session-config
        key: portal_session_conf

secretVolumes:
- kong-cluster-cert

proxy:
  enabled: false

admin:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001
  tls:
    enabled: false
    servicePort: 8001
    containerPort: 8001
    parameters:
    - http2
  ingress:
    enabled: true
    hostname: kong-admin.k3s.local
    path: /

manager:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 8002
    containerPort: 8002
  tls:
    enabled: false
    servicePort: 8002
    containerPort: 8002
    parameters:
    - http2
  ingress:
    enabled: true
    hostname: kong-manager.k3s.local
    path: /

portal:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 8003
    containerPort: 8003
  tls:
    enabled: false
    servicePort: 8003
    containerPort: 8003
    parameters:
    - http2
  ingress:
    enabled: true
    hostname: kong-portal.k3s.local
    path: /

portalapi:
  enabled: true
  type: ClusterIP
  http:
    enabled: true 
    servicePort: 8004
    containerPort: 8004
  tls:
    enabled: false
    servicePort: 8004
    containerPort: 8004
    parameters:
    - http2
  ingress:
    enabled: true
    hostname: kong-portalapi.k3s.local
    path: /

cluster:
  enabled: true
  tls:
    enabled: true
    servicePort: 8005
    containerPort: 8005

clustertelemetry:
  enabled: true
  tls:
    enabled: true
    servicePort: 8006
    containerPort: 8006

enterprise:
  enabled: true
  license_secret: kong-enterprise-license
  vitals:
    enabled: true
  portal:
    enabled: true
  rbac:
    enabled: true
    admin_gui_auth: basic-auth
    session_conf_secret: kong-session-config
  smtp:
    enabled: false

postgresql:
  enabled: true
  postgresqlUsername: kong
  postgresqlPassword: kong
  postgresqlDatabase: kong
  service:
    port: 5432

ingressController:
  enabled: false
  installCRDs: false
