deployment:
  kong:
    enabled: false

ingressController:
  enabled: true
  watchNamespaces:
  - workspace1  # namespace to watch for Kubernetes objects
  env:
    kong_workspace: workspace1 # tells it which Kong workspace to create stuff in
    kong_admin_token:
      valueFrom:
        secretKeyRef:
           name: admin-token-secret  # put your admin token secret info here - same as the other ingress controller has
           key: admin-token-key
    kong_admin_url: https://kong-kong-admin.kong-control-plane.svc.cluster.local:8444 # set this to the Kong control plane you're trying to create resources on
